version: '3'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet

  mongo:
    image: mongo:3.6.21-xenial
    container_name: 'mongodb'
    restart: always
    environment:
      MONGO_INITDB_DATABASE: maid_care_service_database
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - webnet

networks:
  webnet:
volumes:
  mongo_data:
