version: '3'

services:
  backend:
    image: node:14
    volumes:
      - .:/usr/src/app
    command: sh -c 'cd /usr/src/app && yarn && yarn start:dev'
    env_file:
      - .env
    environment:
      NODE_ENV: development
