# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: maid-care-service-backend

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build and Test
      run: |
        npm install --production
        npm build
    # skip test for now
      
  deploy-cloud-run:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCLOUD_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credential: true
      
      - name: Use gcloud CLI
        run: gcloud info

      - name: Configure Docker
        run: |
          gcloud aith configure-docker
        
      - name: Build
        run: |
          docker build -t gcr.io/$${{ GCP_PROJECT_ID }}/werewolf-maid-back:latest .
      
      - name: Push
        run: |
          docker push gcr.io/$${{ GCP_PROJECT_ID }}/werewolf-maid-back:latest
      
      - name: Deploy
        run: |
          gcloud run deploy maid-back \
            --region asia-southeast1 \
            --image gcr.io/$${{ GCP_PROJECT_ID }}/werewolf-maid-back:latest \
            --platform managed
            --allow-unauthenticated
            --project ${{ secrets.GCP_PROJECT_ID }}
