# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backend

on:
  push:
    branches: [ backend ]
  
  workflow_dispatch:

defaults:
  run:
    working-directory: maid-care-service-backend

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install
#       skip test for now
#     - name: Run Test
#       run: npm run test

    - uses: sarisia/actions-status-discord@v1
      if: success()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "Run Test"
        description: "Congrat! Your PR passed the test"
        color: 0x28a745
        username: Werewolf GitHub Actions
    
    - uses: sarisia/actions-status-discord@v1
      if: failure()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "Run Test"
        description: "Sorry, but your is shit!"
        color: 0xd73a49
        username: Werewolf GitHub Actions
        
  build_and_deploy:
    name: Build Docker Image and deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: npm install
      - name: Build Nest Project
        run: npm run build
      - name: Build docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/maid-care-backend:${{ github.sha }} .
          
      - name: Create .env
        run: |
          cat > .env << EOF1
          NODE_ENV=production
          GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
          GCP_SA_KEY=${{ secrets.GCP_SA_KEY_BASE64 }}
          MONGO_URL=${{ secrets.MONGO_URL }}
          SERVER_URL=${{ secrets.SERVER_URL }}
          MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
          SECRET=${{ secrets.SECRET }}
          EOF1
        
      - name: Deploy service to Cloud Run
        uses: stefda/action-cloud-run@v1.0
        with:
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/maid-care-backend:${{ github.sha }}
          service: maid-care-service-backend
          project: ${{ secrets.GCP_PROJECT_ID }}
          region: asia-east1
          env: .env
          service key: ${{ secrets.GCP_SA_KEY_BASE64 }}
      
      - uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "Deploy to Cloud Run"
          description: "Congrat! deploy successfully"
          color: 0x28a745
          username: Werewolf GitHub Actions

      - uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "Deploy to Cloud Run"
          description: "Sorry, something wrong here"
          color: 0xd73a49
          username: Werewolf GitHub Actions
    
