# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backend

on:
  push:
    branches: [ backend ]
  pull_request:
    branches: [ backend ]
  
  workflow_dispatch:

defaults:
  run:
    working-directory: maid-care-service-backend

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install
#       skip test for now
#     - name: Run Test
#       run: npm run test
      
  build_and_deploy:
    name: Build Docker Image and deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: npm run install --production
      - name: Build Nest Project
        run: npm run build
      - name: Build docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/maid-care-backend:${{ github.sha }} .
          
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0.3.0
        with:
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/maid-care-backend:${{ github.sha }}
          service: maid-care-service-backend
          region: asia-southeast1
          env_vars: 
            NODE_ENV=production
            GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
            GCP_SA_KEY=${{ secrets.GCP_SA_KEY }}
            MONGO_URL=${{secrets.MONGO_URL }}
            SECRET=${{ secrets.SECRET }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials: true
    
