# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ frontend ]
  pull_request:
    branches: [ frontend ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: 'frontend'
      
      - name: Setup Node.js environment version ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.4
        with: 
          node-version: ${{ matrix.node_version }}
          
      - name: Route to the Frontend Directory
        run: cd ./maid-care-service-frontend
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build
        run: npm run build --if-present
        
      - name: Run Test
        run: npm run test
  
#   deploy-netlify:
    
#     needs: [build]
    
#     runs-on: ubuntu-latest
    
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           ref: 'frontend'
      
#       - name: Setup Node.js environment
#         uses: actions/setup-node@v2.1.4
#         with: 
#           node-version: 14.x
          
#       - name: Route to the Frontend Directory
#         run: cd ./maid-care-service-frontend
          
#       - name: Install Dependencies
#         run: npm install
      
#       - name: Install Netlify
#         run: npm install netlify-cli -g
        
#       - name: Deploy Netlify
#         run: echo todo;
#         uses: danakim/gh-action-deploy-netlify@master
#         with:
#           AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
#           SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
#           DEPLOY_PROD: true
        
