name: Frontend Workflow

on:
  pull_request:
    branches: [ frontend ]
    
  workflow_dispatch:

defaults:
  run:
    working-directory: maid-care-service-frontend

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:

      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment version ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.4
        with: 
          node-version: ${{ matrix.node_version }}
        
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
          
      - name: Build and Testing
        run: |
          npm ci
          npm run build --if-present
          npm run test
