name: Frontend Deploy Production

on: 
  push:
    branches: [ main ]
    
  workflow_dispatch:
  
defaults:
  run:
    working-directory: maid-care-service-frontend
    
jobs:
  build-and-test:
  
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v2
        
      - name: Setup Node environment version @{{ matrix.node-version }}
        uses: actions/setup-node@2.1.4
        with:
          node-version: ${{ matrix.node_version }}
          
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      
      - name: Build and Testing
        run: |
          yarn install
          yarn build --if-present
          yarn test --passWithNoTests
          
      # Discord Notifications -- Test Before Production Deploy Status
      - uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "Production Deploy - Run Test"
          color: 0x28a745
          username: Werewolf GitHub Actions
      
      - uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "Production Deploy - Run Test"
          color: 0xd73a49
          username: Werewolf GitHub Actions
  
  production-deploy-netlify:
  
    needs: [build-and-test]
    
    runs-on: ubuntu-latest
       
    steps:
    
      - name: Checkout Git Repo
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.4
        with: 
          node-version: 14.x
            
      - name: Build the site
        run: |
          yarn install --production 
          yarn build
      
      - name: Install Netlify
        run: sudo npm install -g netlify-cli --unsafe-perm=true
        
      - name: Netlify Actions
        uses: nwtgck/actions-netlify@v1.1.11
        with:
          production-branch: 'main'
          production-deploy: true
          publish-dir: './maid-care-service-frontend/build/'
          deploy-message: "Deploy Production ${{ github.event.head_commit.message }}"
          netlify-config-path: './maid-care-service-frontend/netlify.toml'
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NODE_ENV: "production"
          REACT_APP_SECRET: ${{ secrets.SECRET }}
          REACT_APP_API_URL: ${{ secrets.SERVER_URL }}
          REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          
      - uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "Deploy Production  on Netlify"
          color: 0x28a745
          username: Werewolf GitHub Actions
      
      - uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "Deploy Production on Netlify"
          color: 0xd73a49
          username: Werewolf GitHub Actions
