name: Backend-Staging

on:
  push:
    branches: [ backend ]
  
  workflow_dispatch:

defaults:
  run:
    working-directory: maid-care-service-backend

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install
#       skip test for now
#     - name: Run Test
#       run: npm run test

    - uses: sarisia/actions-status-discord@v1
      if: success()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "Staging - Run Test"
        color: 0x28a745
        username: Werewolf GitHub Actions
    
    - uses: sarisia/actions-status-discord@v1
      if: failure()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "Staging - Run Test"
        color: 0xd73a49
        username: Werewolf GitHub Actions
        
  build_and_deploy:
    name: Build Docker Image and deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: npm install
      - name: Build Nest Project
        run: npm run build
      - name: Build docker image
        run: docker build -t gcr.io/${{ secrets.STAGING_GCP_PROJECT_ID }}/staging-maid-care-backend:${{ github.sha }} .
          
      - name: Create .env
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_NODE_ENV: "production"
          envkey_GCP_PROJECT_ID: ${{ secrets.STAGING_GCP_PROJECT_ID }}
          envkey_GCP_SA_KEY: ${{ secrets.STAGING_GCP_SA_KEY_BASE64 }}
          envkey_MONGO_URL: ${{ secrets.MONGO_URL }}
          envkey_SERVER_URL: ${{ secrets.STAGING_SERVER_URL }}
          envkey_MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          envkey_MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          envkey_SECRET: ${{ secrets.SECRET }}
      
      - name: Deploy service to Cloud Run
        uses: stefda/action-cloud-run@v1.0
        with:
          image: gcr.io/${{ secrets.STAGING_GCP_PROJECT_ID }}/staging-maid-care-backend:${{ github.sha }}
          service: staging-maid-care-service-backend
          project: ${{ secrets.STAGING_GCP_PROJECT_ID }}
          region: asia-southeast1
          env: .env
          service key: ${{ secrets.STAGING_GCP_SA_KEY_BASE64 }}
      
      - uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "Deploy Staging to Cloud Run"
          description: "Congrat! deploy successfully"
          color: 0x28a745
          username: Werewolf GitHub Actions

      - uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "Deploy to Cloud Run"
          description: "Sorry, something wrong here"
          color: 0xd73a49
          username: Werewolf GitHub Actions
